### ISSUE TITLE
Import guides from previous website

### ISSUE THREAD

**Issue by maxgio92** [projectcapsule/website#3]
This issue tracks the activity of importing the guides from the previous website https://capsule.clastix.io.

**Comment by Svarrogh1337** [comment]
@maxgio92, here is the progress so far in table view.
| capsule.clastix.io                                                                                                              | projectcapsule.dev                                                              | Status |
| ------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- | ------ |
| [Overview](https://capsule.clastix.io/docs/)                                                                                    | [Overview](https://projectcapsule.dev/docs/overview/)                           | ✓      |
| Documentation                                                                                                                   |                                                                                 |        |
| [Getting Started](https://capsule.clastix.io/docs/general/getting-started)                                                      |                                                                                 |        |
| [Tutorial](https://capsule.clastix.io/docs/general/tutorial)                                                                    |                                                                                 |        |
| [References](https://capsule.clastix.io/docs/general/references)                                                                |                                                                                 |        |
| [CRDs APIs](https://capsule.clastix.io/docs/general/crds-apis)                                                                  | [Benchmark](https://projectcapsule.dev/docs/overview/benchmark/)                | ✓      |
| [Multi-Tenant Benchmark](https://capsule.clastix.io/docs/general/mtb)                                                           |                                                                                 |        |
| [Capsule Proxy](https://capsule.clastix.io/docs/general/proxy)                                                                  |                                                                                 |        |
| [Dashboard](https://capsule.clastix.io/docs/general/lens)                                                                       |                                                                                 |        |
| Guides                                                                                                                          |                                                                                 |        |
| [OIDC Authentication](https://capsule.clastix.io/docs/guides/oidc-auth)                                                         | [Authentication](https://projectcapsule.dev/docs/operating/authentication/)     | ✓      |
| [Monitoring Capsule](https://capsule.clastix.io/docs/guides/monitoring)                                                         | [Monitoring Capsule](https://capsule.clastix.io/docs/guides/monitoring)         | Partly |
| [Kubernetes Dashboard](https://capsule.clastix.io/docs/guides/kubernetes-dashboard)                                             |                                                                                 |        |
| [Backup & Restore with Velero](https://capsule.clastix.io/docs/guides/velero)                                                   | [Backup & Restore](https://projectcapsule.dev/docs/operating/backup-restore/)   | ✓      |
| [Upgrading Capsule](https://capsule.clastix.io/docs/guides/upgrading)                                                           | [Upgrading](https://projectcapsule.dev/docs/operating/upgrading/)               | Partly |
| [Multi-tenant GitOps with Flux](https://capsule.clastix.io/docs/guides/flux2-capsule)                                           |                                                                                 |        |
| [Install on Charmed Kubernetes](https://capsule.clastix.io/docs/guides/charmed)                                                 |                                                                                 |        |
| [Control Pod Security](https://capsule.clastix.io/docs/guides/pod-security)                                                     | [Pod Security](https://projectcapsule.dev/docs/operating/control-pod-security/) | ✓      |
| Tenants and Rancher Projects                                                                                                    |                                                                                 |        |
| [Overview](https://capsule.clastix.io/docs/guides/rancher-projects/introduction)                                                |                                                                                 |        |
| [Tenants and Projects](https://capsule.clastix.io/docs/guides/rancher-projects/capsule-rancher)                                 |                                                                                 |        |
| [Rancher Shell and cluster-wide resources](https://capsule.clastix.io/docs/guides/rancher-projects/capsule-proxy-rancher)       |                                                                                 |        |
| [OIDC authentication with Capsule, Rancher and Keycloak](https://capsule.clastix.io/docs/guides/rancher-projects/oidc-keycloak) |                                                                                 |        |
| Managed Kubernetes                                                                                                              |                                                                                 |        |
| [Overview](https://capsule.clastix.io/docs/guides/managed-kubernetes/overview)                                                  |                                                                                 |        |
| [EKS](https://capsule.clastix.io/docs/guides/managed-kubernetes/aws-eks)                                                        |                                                                                 |        |
| [CoAKS](https://capsule.clastix.io/docs/guides/managed-kubernetes/coaks)                                                        |                                                                                 |        |
| Contributing                                                                                                                    |                                                                                 |        |
| [Guidelines](https://capsule.clastix.io/docs/contributing/guidelines)                                                           |                                                                                 |        |
| [Development](https://capsule.clastix.io/docs/contributing/development)                                                         |                                                                                 |        |
| [Governance](https://capsule.clastix.io/docs/contributing/governance)                                                           |                                                                                 |        |
| [Release process](https://capsule.clastix.io/docs/contributing/release)                                                         |                                                                                 |        |
|                                                                                                                                 | [Permissions](https://projectcapsule.dev/docs/tenants/permissions/)             |        |
|                                                                                                                                 | [Namespaces](https://projectcapsule.dev/docs/tenants/namespaces/)               |        |
|                                                                                                                                 | [Quotas](https://projectcapsule.dev/docs/tenants/quotas/)                       |        |
|                                                                                                                                 | [Enforcement](https://projectcapsule.dev/docs/tenants/enforcement/)             |        |
|                                                                                                                                 | [Replications](https://projectcapsule.dev/docs/tenants/replications/)           |        |

**Comment by maxgio92** [comment]
Thank you so much @Svarrogh1337 for that.
